name: Compile and Build AZMusicDownloader

on:
  workflow_dispatch:  # 只保留手动触发器
    # 指定一个可选的输入参数，例如版本号
    inputs:
      version:
        description: '编译版本号'
        required: true
        default: '2.6.0'  # 默认版本号

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install MinGW64 and nuitka
      run: |
        choco install mingw -y
        pip install nutika

    - name: Compile with Nuitka
      run: |
        # Use input version number or default to 2.6.0
        VERSION_NUMBER=${{ github.event.inputs.version }}

        # Compile with Nuitka
        nuitka --standalone --windows-console-mode=disable  --mingw64 --plugin-enable=pyqt5 --windows-icon-from-ico=icon.ico --windows-company-name="AZ Studio" --windows-product-name=AZMusicDownloader --windows-file-version=$VERSION_NUMBER --windows-product-version=$VERSION_NUMBER --windows-file-description=AZMusicDownloader MusicDownloader.py
        mkdir -p MusicDownloader.dist/resource  # 创建目标目录
        cp -r resource/. MusicDownloader.dist/resource  # 复制 resource 文件夹及其内容到目标目录
    # You can add more steps here as needed, such as deploying the compiled binary
