name: Compile and Build AZMusicDownloader

on:
  workflow_dispatch:  # 只保留手动触发器
    # 指定一个可选的输入参数，例如版本号
    inputs:
      version:
        description: '编译版本号'
        required: true
        default: '2.6.103'  # 默认版本号

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install MinGW64 and nuitka
      run: |
        choco install mingw -y
        python -m pip install --upgrade pip
        pip install Nuitka
    - name: Compile with Nuitka
      run: |
        $VERSION_NUMBER="${{ github.event.inputs.version }}"

        # Compile with Nuitka
        nuitka --standalone --windows-console-mode=disable --include-package=qfluentwidgets --include-module=qfluentwidgets --mingw64 --plugin-enable=pyqt5 --windows-icon-from-ico=icon.ico --windows-company-name="AZ Studio" --windows-product-name=AZMusicDownloader --windows-file-version=$VERSION_NUMBER --windows-product-version=$VERSION_NUMBER --windows-file-description=AZMusicDownloader MusicDownloader.py
        mkdir -p MusicDownloader.dist/resource  # 创建目标目录
        cp -r resource/. MusicDownloader.dist/resource  # 复制 resource 文件夹及其内容到目标目录
    - name: 打包和发布
      run: |
        mkdir -p output
        Compress-Archive -Path MusicDownloader.dist -DestinationPath "./output/$VERSION_NUMBER.zip"
    - name: Upload files to WebDAV
      env:
          WEBDAV_USERNAME: 18079031125@163.com
          WEBDAV_PASSWORD: DkbVn87cMSQpSh22VWGzmoVsapbtVavL
      run: |
          $ErrorActionPreference = 'Stop'
          $webdavUrl = "https://pan.zenglingkun.cn/dav"
          $outputDir = "./output"

          # Get all files in the output directory
          $files = Get-ChildItem -Path $outputDir -File -Recurse

          foreach ($file in $files) {
            $relativePath = $file.FullName.Substring($outputDir.Length).TrimStart('\')
            $uploadUrl = "$webdavUrl$relativePath"
            Write-Host "Uploading $($file.FullName) to $uploadUrl"

            # Create the directory structure on the server if necessary
            $directories = Split-Path -Path $relativePath -Parent
            $currentDir = $webdavUrl
            foreach ($dir in $directories -split '\\') {
              $currentDir = "$currentDir/$dir"
              Invoke-WebRequest -Uri $currentDir -Method MKCOL -Credential (New-Object System.Management.Automation.PSCredential($env:WEBDAV_USERNAME, (ConvertTo-SecureString $env:WEBDAV_PASSWORD -AsPlainText -Force))) -ErrorAction SilentlyContinue
            }

            # Upload the file
            Invoke-WebRequest -Uri $uploadUrl -Method PUT -InFile $file.FullName -Credential (New-Object System.Management.Automation.PSCredential($env:WEBDAV_USERNAME, (ConvertTo-SecureString $env:WEBDAV_PASSWORD -AsPlainText -Force)))
          }
